-- Seed stations
INSERT INTO "Station" (id, name, "streamUrl", category, "isLive", "createdAt", "updatedAt") VALUES
('station_1', '101.1Megasite', 'http://37.247.98.8/stream/30/', 'Pop & Hit', true, now(), now()),
('station_2', '102.1 Arabeskin Merkezi Fm', 'https://canli.arabeskinmerkezi.com:9180/listen.pls', 'Arabesk & Nostalji', true, now(), now()),
('station_3', '107.4 Radio Voyage', 'https://dygedge.radyotvonline.net/radyovoyage/playlist.m3u8?listenerid=29d0a6a85b59cea2ca801b70d2a3ebaf&awparams=companionAds%3Atrue', 'Pop & Hit', true, now(), now()),
('station_4', '90 lar Pop', 'https://moondigitaledge.radyotvonline.net/radyolanddoksanlar/playlist.m3u8', 'Arabesk & Nostalji', true, now(), now()),
('station_5', '90LAR', 'https://moondigitaledge.radyotvonline.net/90lar/playlist.m3u8', 'Arabesk & Nostalji', true, now(), now()),
('station_6', '90lar turkey', 'http://37.247.98.8/stream/166/', 'Arabesk & Nostalji', true, now(), now()),
('station_7', '95.1 TEMPO RADYO HATAY', 'https://sslyayin.netyayin.net/tempo/stream', 'Yerel', true, now(), now()),
('station_8', 'A Haber', 'https://trkvz-radyolar.ercdn.net/ahaberradyo/playlist.m3u8', 'Haber', true, now(), now()),
('station_9', 'A spor', 'https://trkvz-radyolar.ercdn.net/asporradyo/chunklist.m3u8', 'Spor', true, now(), now()),
('station_10', 'ADANA FM', 'https://host.onlineradyotv.net:2020/stream/adanafm', 'Yerel', true, now(), now()),
('station_11', 'AFN 360 Incirlik', 'http://playerservices.streamtheworld.com/m3u/AFNE_ICK.m3u', 'Yerel', true, now(), now()),
('station_12', 'AFN İNCİRLİK', 'https://playerservices.streamtheworld.com/api/livestream-redirect/AFNE_ICK.mp3', 'Yerel', true, now(), now()),
('station_13', 'AKTİF FM', 'https://radyo.yayindakiler.com:3164/stream', 'Yerel', true, now(), now()),
('station_14', 'ALEM FM', 'https://edge1.radyotvonline.net/shoutcast/play/alemfm', 'Pop & Hit', true, now(), now()),
('station_15', 'ALTIN SARKILAR', 'http://37.247.98.8/listen.pls?sid=25', 'Arabesk & Nostalji', true, now(), now()),
('station_16', 'ALTIN ŞARKILAR', 'https://moondigitalmaster.radyotvonline.net/altinsarkilar/playlist.m3u8', 'Arabesk & Nostalji', true, now(), now()),
('station_17', 'ANTAKYA RENK FM HATAY', 'https://radyo.yayindakiler.com:3016/renk', 'Yerel', true, now(), now()),
('station_18', 'ASPOR', 'http://trkvz-radyolar.ercdn.net/asporradyo/playlist.m3u8', 'Spor', true, now(), now()),
('station_19', 'Abuzer FM', 'http://live.radyotvonline.com:9030/;stream.nsv', 'Yerel', true, now(), now()),
('station_20', 'Ahaber', 'http://trkvz-radyolar.ercdn.net/ahaberradyo/chunklist.m3u8', 'Haber', true, now(), now()),
('station_21', 'Akra FM', 'https://d3r5bwwuab2v60.cloudfront.net/akracanli2/_definst_/livestream_aac/playlist.m3u8', 'Dini', true, now(), now()),
('station_22', 'Alem FM', 'http://turkmedya.radyotvonline.com/turkmedya/alemfm.stream/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_23', 'Alem Fm', 'https://turkmedya.radyotvonline.net/alemfmaac', 'Pop & Hit', true, now(), now()),
('station_24', 'Ankara Havalari', 'http://37.247.98.8/listen.pls?sid=30', 'Türkü & Halk', true, now(), now()),
('station_25', 'Apacik Radyo', 'http://stream.34bit.net/ar.aac', 'Yerel', true, now(), now()),
('station_26', 'Arabesk FM', 'http://yayin.arabeskfm.biz:8042/', 'Arabesk & Nostalji', true, now(), now()),
('station_27', 'Arkadas Radyo', 'http://yayin2.yayindakiler.com:4134/;stream.nsv', 'Yerel', true, now(), now()),
('station_28', 'Avrasya Türk Radyo', 'https://sslyayin.netyayin.net:10909/', 'Pop & Hit', true, now(), now()),
('station_29', 'Axa Rojava', 'https://stream.zeno.fm/h6mn2c8ha8zuv', 'Kürtçe', true, now(), now()),
('station_30', 'Azadi Fm', 'https://amed.ozelip.com/8040/;', 'Kürtçe', true, now(), now()),
('station_31', 'AÇS Radyo', 'https://ip169.ozelip.com:10838/', 'Yerel', true, now(), now()),
('station_32', 'Aşk FM', 'http://yayin.asymedya.com:8020/;', 'Arabesk & Nostalji', true, now(), now()),
('station_33', 'BABYLAND TURKEY', 'https://moondigitaledge.radyotvonline.net/babyland/playlist.m3u8', 'Çocuk', true, now(), now()),
('station_34', 'BANAZ DOST FM', 'https://sssx.radyosfer.com/banazdostfm/stream', 'Yerel', true, now(), now()),
('station_35', 'BARIŞ FM', 'https://sslyayin.netyayin.net:10990/', 'Yerel', true, now(), now()),
('station_36', 'BATI RADYO', 'https://sslyayin.netyayin.net:10902/', 'Yerel', true, now(), now()),
('station_37', 'BAU RADYO', 'https://ssl120.radyotelekom.com.tr/8106/stream.mp4', 'Klasik & Kültür', true, now(), now()),
('station_38', 'BAYRAM FM TURKEY', 'https://sslyayin.netyayin.net/3442/stream', 'Yerel', true, now(), now()),
('station_39', 'BEST HİT', 'https://wowza3.radyotvonline.com/best/bestteen.stream/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_40', 'BEST KINA', 'https://wowza3.radyotvonline.com/best/bestkina.stream/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_41', 'BEST RAP', 'https://wowza3.radyotvonline.com/best/bestgicir.stream/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_42', 'BEST SLOW', 'https://hepsibest.radyotvonline.net/bestslow', 'Pop & Hit', true, now(), now()),
('station_43', 'BOĞAZ FM', 'https://radyo.yayin.com.tr:5938/', 'Yerel', true, now(), now()),
('station_44', 'BRTK', 'http://sc.brtk.net:8000/', 'Yerel', true, now(), now()),
('station_45', 'BURDUR FM', 'https://sssx.radyosfer.com/burdurfm/stream', 'Yerel', true, now(), now()),
('station_46', 'BURSA FM', 'https://radyo.yayin.com.tr:1055/', 'Yerel', true, now(), now()),
('station_47', 'Baba Radyo', 'https://babaradyo.turkhosted.com/best/babaradyo.stream/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_48', 'Banko Fm 1', 'http://yayin.netradyom.com:9910/RADYOBANKO', 'Yerel', true, now(), now()),
('station_49', 'Bayram FM', 'https://sslyayin.netyayin.net:10962/320.mp3', 'Yerel', true, now(), now()),
('station_50', 'Best FM', 'https://ssldyg.radyotvonline.com/best/bestfm.stream/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_51', 'BesteFM', 'https://stream.zeno.fm/tnvnovtgozstv', 'Pop & Hit', true, now(), now()),
('station_52', 'BesteFM Mix', 'https://yayin.radyomadyo.com:8002/', 'Pop & Hit', true, now(), now()),
('station_53', 'Beyaz TV', 'https://beyaztv-live.daioncdn.net/beyaztv/beyaztv_1080p.m3u8', 'TV (Video)', true, now(), now()),
('station_54', 'Bizim Radyo', 'https://ip132.ozelip.com:7017/', 'Yerel', true, now(), now()),
('station_55', 'BloombergHTradyo', 'https://ciner-live.ercdn.net/bloombergradyo/bloombergradyo_1.m3u8', 'Haber', true, now(), now()),
('station_56', 'Bodrum Fm', 'https://live.bodrumfm.org/stream.mp3', 'Yerel', true, now(), now()),
('station_57', 'Borusan Klasik', 'http://provisioning.streamtheworld.com/pls/BORUSAN_KLASIKAAC.pls', 'Klasik & Kültür', true, now(), now()),
('station_58', 'BİGA FM', 'https://radyo.yayin.com.tr:5896/', 'Yerel', true, now(), now()),
('station_59', 'BİLECİK FM TURKEY', 'http://bilecikfm.kesintisizyayin.com:9980/', 'Yerel', true, now(), now()),
('station_60', 'CEMRE FM', 'https://yayin2.canliyayin.org:8024/', 'Yerel', true, now(), now()),
('station_61', 'CLASSICLAND TURKEY', 'https://moondigitaledge.radyotvonline.net/classicland/playlist.m3u8', 'Klasik & Kültür', true, now(), now()),
('station_62', 'COFFEE PROJECT RADYO', 'https://radyo.yayin.com.tr:5926/', 'Yerel', true, now(), now()),
('station_63', 'Can Radyo', 'http://yayin1.yayindakiler.com:3124/;', 'Pop & Hit', true, now(), now()),
('station_64', 'Can Tv', 'https://livetv.canbroadcast.com:7443/canlican/tv.m3u8', 'TV (Video)', true, now(), now()),
('station_65', 'Cantürk Radyo', 'https://moondigitaledge2.radyotvonline.net/cnnturk/playlist.m3u8?listeningSessionID=669e367246737fe5_6249184_Zq120UIn__0000001w2Bs&downloadSessionID=0', 'Haber', true, now(), now()),
('station_66', 'DADA RADYO', 'http://stream.laut.fm/dadaradio', 'Yerel', true, now(), now()),
('station_67', 'DAMAR TURK FM', 'https://live.radyositesihazir.com:10997/', 'Arabesk & Nostalji', true, now(), now()),
('station_68', 'DEDEMİN RADYOSU', 'https://anadolu.liderhost.com.tr/9002/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_69', 'DENİZ FM', 'https://sssx.radyosfer.com/denizfm/stream', 'Yerel', true, now(), now()),
('station_70', 'DERYA FM', 'https://yayin.turkhosted.com:6032/', 'Yerel', true, now(), now()),
('station_71', 'DO U FM', 'https://sslyayin.netyayin.net:10935/', 'Yerel', true, now(), now()),
('station_72', 'DOLU RADYO', 'https://sslyayin.radyoyayini.com:7070/', 'Yerel', true, now(), now()),
('station_73', 'DOĞAN 21', 'https://radyo.yayindakiler.com:3024/', 'Yerel', true, now(), now()),
('station_74', 'DREAM TÜRK', 'https://radyo.duhnet.tv/dreamturk', 'Pop & Hit', true, now(), now()),
('station_75', 'DT NOSTALJİ', 'https://canli.dtnostalji.com.tr/9999/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_76', 'Dadaş Fm Erzurum', 'https://sslyayin.netyayin.net:8084/stream/;stream.mp3', 'Arabesk & Nostalji', true, now(), now()),
('station_77', 'Damar Turk FM', 'https://live.radyositesihazir.com:10997/;', 'Arabesk & Nostalji', true, now(), now()),
('station_78', 'DamarTurk FM', 'https://live.radyositesihazir.com:10997/stream?type=http&nocache=99881', 'Arabesk & Nostalji', true, now(), now()),
('station_79', 'DanceLand Anthems', 'https://likeradiostream.com/dancelandanthems', 'Dance & Elektronik', true, now(), now()),
('station_80', 'Danceland', 'https://moondigitaledge.radyotvonline.net/danceland/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_81', 'DateLine IP', 'https://stream.datelineip.com/hls/datelineip/live.m3u8', 'Genel', true, now(), now()),
('station_82', 'Denge Gundeme', 'http://kesintisizyayin.com:1656/', 'Kürtçe', true, now(), now()),
('station_83', 'Dijital radyo', 'https://anadolu.liderhost.com.tr:10961/;', 'Yerel', true, now(), now()),
('station_84', 'Discoland', 'https://moondigitaledge.radyotvonline.net/discoland/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_85', 'Diyarbakır Çağrı FM', 'https://live.cagrifm.com.tr/cagrifm', 'Kürtçe', true, now(), now()),
('station_86', 'Dost', 'http://yayin1.yayindakiler.com:3156/', 'Yerel', true, now(), now()),
('station_87', 'Dost FM', 'http://yayin.dostfm.com:8920/;.mp3?no_dl', 'Yerel', true, now(), now()),
('station_88', 'Dost Radyo', 'http://yayin1.yayindakiler.com:3156/;', 'Yerel', true, now(), now()),
('station_89', 'Doğan 22', 'http://yayin1.yayindakiler.com:3024/;', 'Yerel', true, now(), now()),
('station_90', 'Doğu Radyo', 'http://198.7.59.28:8146/', 'Türkü & Halk', true, now(), now()),
('station_91', 'DÜNYADAN SESLER', 'https://stream.radiojar.com/cg24hdbwa0hvv', 'Klasik & Kültür', true, now(), now()),
('station_92', 'EFSANE 4LÜ TURKEY', 'https://moondigitalmaster.radyotvonline.net/efsane4lu/playlist.m3u8', 'Arabesk & Nostalji', true, now(), now()),
('station_93', 'EFSANE HOME', 'http://37.247.98.8/stream/24/', 'Arabesk & Nostalji', true, now(), now()),
('station_94', 'EGE HAVALARI TURKEY', 'https://moondigitalmaster.radyotvonline.net/egehavalari/playlist.m3u8', 'Türkü & Halk', true, now(), now()),
('station_95', 'EGE KAMPÜS', 'https://stream.ege.edu.tr/hls/rek.m3u8', 'Klasik & Kültür', true, now(), now()),
('station_96', 'ERT ELAZIĞ', 'https://radyo.yayin.com.tr:8012/', 'Yerel', true, now(), now()),
('station_97', 'ERZİNCAN FM', 'https://sslyayin.netyayin.net:10943/', 'Yerel', true, now(), now()),
('station_98', 'EVRENSEL FM', 'https://ssl16.ozelip.com/asistan/stream/914fcb8228b91c6fe05b3bd0fa85299c', 'Yerel', true, now(), now()),
('station_99', 'EZGİ RADYO', 'https://radyo.yayindakiler.com:3044/;', 'Arabesk & Nostalji', true, now(), now()),
('station_100', 'Easyland', 'https://moondigitaledge.radyotvonline.net/easyland/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_101', 'Elazığ Mavi Radyo', 'https://yayin.turkhosted.com/6066/stream', 'Yerel', true, now(), now()),
('station_102', 'Emek radyo', 'http://yayin1.radyohizmeti.com:8585/;', 'Yerel', true, now(), now()),
('station_103', 'Enderun FM', 'http://yayin2.canliyayin.org:7052/;*.mp3', 'Klasik & Kültür', true, now(), now()),
('station_104', 'Engelliler radyo', 'https://stream.zeno.fm/iuqovax9ftsvv', 'Genel', true, now(), now()),
('station_105', 'Ereğli FM', 'http://radyo.yayindakiler.com:3000/stream', 'Yerel', true, now(), now()),
('station_106', 'Erkam Radyo', 'https://api-tv5.yayin.com.tr:8002/mp3', 'Dini', true, now(), now()),
('station_107', 'Erkam Radyo 2nd Stream', 'https://yayin2.canliyayin.org:10910/stream?', 'Dini', true, now(), now()),
('station_108', 'Erzincan Cem Radyo', 'https://erzincan.80.yayin.com.tr/stream', 'Yerel', true, now(), now()),
('station_109', 'Erzincan Nostalji Radyo', 'https://erzincannostalji.ozelip.com/8238/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_110', 'Esas radyo', 'https://yayin.turkhosted.com:6034/stream/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_111', 'FENOMEN AKUSTIK', 'https://live.radyofenomen.com/fenomenakustik/abr/fenomenakustik/128/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_112', 'FENOMEN DANS', 'https://live.radyofenomen.com/fenomendans/abr/fenomendans/128/chunks.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_113', 'FENOMEN KARISIK', 'https://live.radyofenomen.com/fenomenkarisik/abr/fenomenkarisik/128/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_114', 'FENOMEN POP', 'https://live.radyofenomen.com/fenomenpop/abr/fenomenpop/128/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_115', 'FENOMEN RAP', 'https://live.radyofenomen.com/fenomenrap/abr/fenomenrap/128/chunks.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_116', 'FENOMEN TÜRK', 'https://live.radyofenomen.com/fenomenturk/abr/fenomenturk/256/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_117', 'FG 93.8 (Future Generation) mp3 128k', 'https://edge1.radyotvonline.net/shoutcast/play/fg', 'Dance & Elektronik', true, now(), now()),
('station_118', 'FIND A CUTİE', 'https://stream.zeno.fm/lyl2uv7fcvovv', 'Pop & Hit', true, now(), now()),
('station_119', 'FLOW RADYO', 'https://moondigitaledge.radyotvonline.net/flow/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_120', 'FRİGBO', 'https://station.frigbo.com/listen/frigbo/radio.mp3', 'Dance & Elektronik', true, now(), now()),
('station_121', 'FULL FM', 'https://listen.powerapp.com.tr/powerdance/abr/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_122', 'Fakir Fm', 'https://live.radyositesihazir.com/1025/stream/', 'Yerel', true, now(), now()),
('station_123', 'Fenerbahce Radyo', 'http://91.232.174.18:8000/Stream', 'Spor', true, now(), now()),
('station_124', 'Fenomen 2010''lar 256', 'https://live.radyofenomen.com/fenomen2010/256/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_125', 'Fenomen 256', 'https://live.radyofenomen.com/fenomen/256/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_126', 'Fenomen Clubbin 256', 'https://live.radyofenomen.com/fenomenclubbin/256/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_127', 'Fenomen Dans 256', 'https://live.radyofenomen.com/fenomendans/256/chunks.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_128', 'Fenomen Karışık 256', 'https://live.radyofenomen.com/fenomenkarisik/256/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_129', 'Fenomen Pop 256', 'https://live.radyofenomen.com/fenomenpop/256/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_130', 'Fenomen Türk 256', 'https://live.radyofenomen.com/fenomenturk/256/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_131', 'Fırat FM', 'https://anadolu.liderhost.com.tr:10912/;', 'Yerel', true, now(), now()),
('station_132', 'GARAJ RADYO', 'https://moondigitaledge.radyotvonline.net/garajradyo/playlist.m3u8', 'Rock & Alternatif', true, now(), now()),
('station_133', 'GENÇ KRAL FM', 'https://anadolu.liderhost.com.tr:10853/;', 'Pop & Hit', true, now(), now()),
('station_134', 'GENÇ RADYO', 'https://yayin.turkhosted.com:6030/', 'Pop & Hit', true, now(), now()),
('station_135', 'GENÇLİK RADYOSU', 'https://canli.radyogenclik.com:9000/', 'Pop & Hit', true, now(), now()),
('station_136', 'GREEKLAND', 'https://moondigitaledge.radyotvonline.net/greekland/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_137', 'GURBETCİ FM', 'https://sssx.radyosfer.com/gurbetcifm/', 'Pop & Hit', true, now(), now()),
('station_138', 'Genç FM', 'https://yayin1.canlitv.fun/radyo/gencfm/chunklist_w1257533803.m3u8', 'Pop & Hit', true, now(), now()),
('station_139', 'Giresun FM', 'http://yayin.canliyayin.org:9482/;', 'Yerel', true, now(), now()),
('station_140', 'Govend radyo', 'https://stream-56.zeno.fm/xzzu8kynq2zuv?zs=nZP7ZCRXQPOpDFenayr0bQ', 'Kürtçe', true, now(), now()),
('station_141', 'Gundi Fm', 'http://gundifm.ozelip.com:7830/;', 'Kürtçe', true, now(), now()),
('station_142', 'GÖKKUŞAĞI RADYO TURKEY', 'http://gokkusagiradyo.kesintisizyayin.com:8008/', 'Çocuk', true, now(), now()),
('station_143', 'Göl Radyo', 'https://28553.live.streamtheworld.com/SUPER_FM_ITUNES.mp3', 'Pop & Hit', true, now(), now()),
('station_144', 'Gözyaşı FM', 'http://yayin1.canliyayin.org:8700/;*.mp3', 'Arabesk & Nostalji', true, now(), now()),
('station_145', 'Gül Fm', 'https://yayin2.canliyayin.org:10989/;*.mp3', 'Pop & Hit', true, now(), now()),
('station_146', 'GİMSA RADYO', 'http://yayin1.canliyayin.org:9482/stream', 'Yerel', true, now(), now()),
('station_147', 'HABER TÜRK RADYO', 'https://haberturkradyo.radyotvonline.net/haberturkradyo', 'Haber', true, now(), now()),
('station_148', 'HAYAL FM', 'https://panel.radyomhd.com:8050/', 'Arabesk & Nostalji', true, now(), now()),
('station_149', 'HAYAT MİX SLOW', 'https://radyo.yayin.com.tr:4090/mp3', 'Arabesk & Nostalji', true, now(), now()),
('station_150', 'HAYATMİX', 'https://hayatmix.yayin.com.tr/mp3', 'Pop & Hit', true, now(), now()),
('station_151', 'HAYATMİX ARABESK', 'https://radyo.yayin.com.tr:4078/mp3', 'Arabesk & Nostalji', true, now(), now()),
('station_152', 'HEY RADYO', 'https://usa4.fastcast4u.com/proxy/radyoizmirfm/', 'Pop & Hit', true, now(), now()),
('station_153', 'HOME KLASİK TURKEY', 'https://ssl4.radyotvonline.com/radyohome/klasikhome.stream_aac/playlist.m3u8', 'Klasik & Kültür', true, now(), now()),
('station_154', 'HOS MİX', 'https://anadolu.liderhost.com.tr:10871/', 'Pop & Hit', true, now(), now()),
('station_155', 'HOUSELAND TURKEY', 'https://moondigitaledge.radyotvonline.net/houseland/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_156', 'Haber Türk Radyo', 'http://haberturkradyo.radyotvonline.net/haberturkradyo', 'Haber', true, now(), now()),
('station_157', 'Habertürk Radyo', 'https://ciner.daioncdn.net/haberturktv/haberturktv_1080p.m3u8?sid=67dy0kx38l3a&app=c98ab0b0-50cc-495b-bb37-778e91f5ff5b&ce=3', 'TV (Video)', true, now(), now()),
('station_158', 'Halk Radyo', 'https://anadolu.liderhost.com.tr:10876/;', 'Türkü & Halk', true, now(), now()),
('station_159', 'Halk Tv', 'https://halktv.daioncdn.net/halktv/halktv_1080p.m3u8?sid=6vahxsup0jxl&app=c86957d3-74a7-44da-9ad2-dc358c769609&ce=3', 'TV (Video)', true, now(), now()),
('station_160', 'Havin FM', 'http://yayin6.radyohizmeti.com:7050/;stream.mp3', 'Kürtçe', true, now(), now()),
('station_161', 'Hemdem Radyo', 'https://yayin.hemdemradyo.com/', 'Kürtçe', true, now(), now()),
('station_162', 'Her An Kur''an Her An Mutluluk', 'https://radio.mihr.com/radio/8050/radio.mp3', 'Dini', true, now(), now()),
('station_163', 'JOY TÜRK FM', 'https://playerservices.streamtheworld.com/api/livestream-redirect/JOY_TURK_ITUNES.mp3', 'Pop & Hit', true, now(), now()),
('station_164', 'JOY TÜRK ROCK TURKEY', 'https://playerservices.streamtheworld.com/api/livestream-redirect/JOYTURK_ROCK_SC?/', 'Rock & Alternatif', true, now(), now()),
('station_165', 'JOY TÜRK TURKEY', 'https://playerservices.streamtheworld.com/api/livestream-redirect/JOY_TURK_SC?/', 'Pop & Hit', true, now(), now()),
('station_166', 'Joy FM Istanbul', 'http://21633.live.streamtheworld.com/JOY_FM128AAC.aac', 'Pop & Hit', true, now(), now()),
('station_167', 'Joy Fm', 'http://provisioning.streamtheworld.com/pls/JOY_FMAAC.pls', 'Pop & Hit', true, now(), now()),
('station_168', 'JoyTürk Akustik', 'http://playerservices.streamtheworld.com/api/livestream-redirect/JOYTURK_AKUSTIK128AAC.aac', 'Pop & Hit', true, now(), now()),
('station_169', 'JoyTürk Rock', 'http://23613.live.streamtheworld.com/JOYTURK_ROCK128AAC.aac', 'Rock & Alternatif', true, now(), now()),
('station_170', 'KARMA TÜRK', 'https://yayin.radyomadyo.com:8006/stream', 'Pop & Hit', true, now(), now()),
('station_171', 'KARMA TÜRK SLOW', 'https://yayin.radyomadyo.com:8004/stream', 'Pop & Hit', true, now(), now()),
('station_172', 'KENT RADYO', 'https://anadolu.liderhost.com.tr:10906/', 'Yerel', true, now(), now()),
('station_173', 'KEYF STATION', 'http://yayin.radyomadyo.com:8002/stream', 'Pop & Hit', true, now(), now()),
('station_174', 'KISS SPEED UP', 'https://dijimedya.radyotvonline.net/speedup', 'Pop & Hit', true, now(), now()),
('station_175', 'KIYI Muzik', 'https://kiyi.radioca.st/stream', 'Pop & Hit', true, now(), now()),
('station_176', 'KIYI Turkce', 'https://kiyiturk.radioca.st/stream', 'Türkü & Halk', true, now(), now()),
('station_177', 'KLAS RADİO TURKEY', 'https://anadolu.liderhost.com.tr:10929/', 'Klasik & Kültür', true, now(), now()),
('station_178', 'KLASİK HOME', 'http://37.247.98.8/stream/32/', 'Klasik & Kültür', true, now(), now()),
('station_179', 'KRAL FM', 'https://dygedge2.radyotvonline.net/kralfm/playlist.m3u8?listenerid=29d0a6a85b59cea2ca801b70d2a3ebaf&awparams=companionAds%3Atrue', 'Pop & Hit', true, now(), now()),
('station_180', 'KRAL POP ALTERNATİF 2', 'https://ssldyg.radyotvonline.com/smil/smil:kralpop.smil/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_181', 'KRAL TÜRK FM', 'https://live.radyositesihazir.com/8032/stream', 'Pop & Hit', true, now(), now()),
('station_182', 'KTU', 'https://sslyayin.netyayin.net/radyoktu/stream/;type=mp3', 'Klasik & Kültür', true, now(), now()),
('station_183', 'KUZEY FM TURKEY', 'http://yayin.yayindakiler.com:3028/', 'Pop & Hit', true, now(), now()),
('station_184', 'Kafa Radyo', 'https://moondigitalmaster.radyotvonline.net/kafaradyo/playlist.m3u8', 'Rock & Alternatif', true, now(), now()),
('station_185', 'Kalp FM', 'https://yayin.kalpfm.com:8080/', 'Pop & Hit', true, now(), now()),
('station_186', 'Karadeniz FM', 'https://moondigitaledge.radyotvonline.net/karadenizfm/playlist.m3u8', 'Yerel', true, now(), now()),
('station_187', 'Karadut Fm', 'https://yayin5.radyohizmeti.com/9982/stream', 'Pop & Hit', true, now(), now()),
('station_188', 'Kent FM', 'https://moondigitalmaster.radyotvonline.net/kentfm/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_189', 'Kiss Türk', 'https://kiss.radyotvonline.net/kissturk', 'Pop & Hit', true, now(), now()),
('station_190', 'Konya İsra FM', 'https://yayin2.canliyayin.org:8210/;stream', 'Yerel', true, now(), now()),
('station_191', 'Kurd1', 'https://www.radioking.com/play/kurd1-radyo', 'Kürtçe', true, now(), now()),
('station_192', 'Köroğlu FM', 'https://yayin.turkhosted.com:6068/stream?/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_193', 'Küpe FM', 'https://icecast.netmedya.net/kupefm', 'Kürtçe', true, now(), now()),
('station_194', 'KİSS GENÇ', 'https://dijimedya.radyotvonline.net/gncradyo', 'Pop & Hit', true, now(), now()),
('station_195', 'KİSS GOLD TÜRK', 'https://dijimedya.radyotvonline.net/goldturk', 'Pop & Hit', true, now(), now()),
('station_196', 'KİSS LOVE RADYO TURKEY', 'https://anadolu.liderhost.com.tr:10964/', 'Pop & Hit', true, now(), now()),
('station_197', 'KİSS MUSİKİ', 'https://dijimedya.radyotvonline.net/radyomusiki', 'Klasik & Kültür', true, now(), now()),
('station_198', 'KİSS SLOW', 'https://radyo.slmbilisim.net/8004/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_199', 'KİSS TÜRK SLOW', 'http://dijimedya.radyotvonline.net/turkslow', 'Pop & Hit', true, now(), now()),
('station_200', 'Kıyı Caz', 'http://caz.radioca.st/', 'Klasik & Kültür', true, now(), now()),
('station_201', 'Kıyı Gece', 'https://gece.radioca.st/stream', 'Pop & Hit', true, now(), now()),
('station_202', 'Kıyı Türkçe', 'https://kiyiturk.radioca.st/', 'Türkü & Halk', true, now(), now()),
('station_203', 'LALEGÜL FM', 'https://icecast.netmedya.net/lalegulfm', 'Dini', true, now(), now()),
('station_204', 'LATERADİO', 'https://radio.lateradio.live/;', 'Pop & Hit', true, now(), now()),
('station_205', 'LP Roman Fm', 'https://stream.zeno.fm/netvowp5t54uv.m3u', 'Pop & Hit', true, now(), now()),
('station_206', 'Lig Radyo', 'https://ligradyo.radyotvonline.net/ligradyo', 'Spor', true, now(), now()),
('station_207', 'Loops Radio Elektronica Station', 'https://ssl22.radyotelekom.com/8232/stream', 'Dance & Elektronik', true, now(), now()),
('station_208', 'Loops Radio House Station', 'https://loopsdeep.ozelip.com/7806/stream', 'Dance & Elektronik', true, now(), now()),
('station_209', 'Loops Radio Techno', 'https://ip179.ozelip.com/7688//asistan/stream/', 'Dance & Elektronik', true, now(), now()),
('station_210', 'MASAL RADYO', 'https://radyoserver3.okeylisans.com:14000/8552/;', 'Çocuk', true, now(), now()),
('station_211', 'MASTİKA FM', 'https://mastika1.80.yayin.com.tr/', 'Pop & Hit', true, now(), now()),
('station_212', 'MAZİDEN BİR DEMET', 'http://37.247.98.8/stream/25/', 'Arabesk & Nostalji', true, now(), now()),
('station_213', 'MEGA SİTE', 'http://yayin.netradyom.com:7900/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_214', 'MEGASITE', 'https://stream.netradyom.com/listen/megasite/radio.mp3', 'Pop & Hit', true, now(), now()),
('station_215', 'MELANKOLİK HOME', 'http://37.247.98.8/stream/20/', 'Arabesk & Nostalji', true, now(), now()),
('station_216', 'MELODİ RADYO', 'https://radyomelodi.80.yayin.com.tr/', 'Pop & Hit', true, now(), now()),
('station_217', 'MERKEZ FM SAMSUN TURKEY', 'http://uydu.radyotvyayini.com:8016/', 'Yerel', true, now(), now()),
('station_218', 'MOOD ROCK', 'https://radyo.yayin.com.tr:6321/;', 'Rock & Alternatif', true, now(), now()),
('station_219', 'MPL Radyo', 'https://canli.hidayetradyolari.com/listen/mpl_radyo/radio.mp3', 'Pop & Hit', true, now(), now()),
('station_220', 'Magic FM', 'http://yayin1.yayindakiler.com:3032/', 'Pop & Hit', true, now(), now()),
('station_221', 'Max FM', 'http://live2.radyotvonline.com:8025/', 'Pop & Hit', true, now(), now()),
('station_222', 'Max Fm 95.8 ‘Maximum Music''', 'https://maxfm.radyotvonline.net/stream/164/;', 'Pop & Hit', true, now(), now()),
('station_223', 'MaxFM', 'http://live.radyotvonline.com:8090/;', 'Pop & Hit', true, now(), now()),
('station_224', 'Mayday Records', 'https://stream.maydayrecords.net/radio/8000/maydayrecords.mp3', 'Dance & Elektronik', true, now(), now()),
('station_225', 'Med Radyo', 'http://medradyo.kesintisizyayin.com:8062/listen.pls', 'Kürtçe', true, now(), now()),
('station_226', 'Mega Ask FM', 'https://embed.tawk.to/_s/v4/assets/audio/chat_sound.mp3', 'Arabesk & Nostalji', true, now(), now()),
('station_227', 'Mega Site', 'http://yayin.netradyom.com:7900/;', 'Pop & Hit', true, now(), now()),
('station_228', 'Mega Site .', 'http://yayin.netradyom.com:7900/;stream.mp3RADYO%20MEGAS%C4%B0TE%20=', 'Pop & Hit', true, now(), now()),
('station_229', 'Mekke Fm', 'https://radyodinle.cansuyufm.com/17175/stream;', 'Dini', true, now(), now()),
('station_230', 'Metro FM', 'http://28503.live.streamtheworld.com:3690/METRO_FMAAC_SC', 'Pop & Hit', true, now(), now()),
('station_231', 'Metro fm turkey', 'https://playerservices.streamtheworld.com/api/livestream-redirect/METRO_FM_SC?', 'Pop & Hit', true, now(), now()),
('station_232', 'Mio Radio', 'https://s2.myradiostream.com/13662/;?type=http&nocache=1769756485?0.283950275860107', 'Pop & Hit', true, now(), now()),
('station_233', 'Mix A Mix FM', 'https://radyo.yayin.com.tr:5998/stream/1/?icy=http', 'Pop & Hit', true, now(), now()),
('station_234', 'Moral FM', 'https://stream-157.zeno.fm/0cfiqwdkobavv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIwY2ZpcXdka29iYXZ2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ik1kcEtfTUtQUm5xS3N4Mk8yXzl5YnciLCJpYXQiOjE3MzEyNzQ1ODIsImV4cCI6MTczMTI3NDY0Mn0.0eDtTzJb2qydtHkWls4Op4nmAZvg_Q9AyObMw0XOy50', 'Dini', true, now(), now()),
('station_235', 'Mydonose Türk', 'https://27913.live.streamtheworld.com/MYDONOSE_TURK128AAC.aac?/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_236', 'NTV Radyo', 'http://ntvrdwmp.radyotvonline.com/', 'Haber', true, now(), now()),
('station_237', 'NUMBER ONE TURK AJDA PEKKAN', 'https://n10101m.mediatriple.net/videoonlylive/mtkgeuihrlfwlive/u_stream_5c9e3ed520608_1/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_238', 'NUMBER ONE WORLD', 'https://n10101m.mediatriple.net/videoonlylive/mtkgeuihrlfwlive/u_stream_5c9e2f95dcb16_1/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_239', 'NUR Radyo', 'https://canli.hidayetradyolari.com/listen/radyo_nur/radio.mp3', 'Dini', true, now(), now()),
('station_240', 'Number 1 Türk Rap', 'https://dijimedya.radyotvonline.net/turkrap', 'Dance & Elektronik', true, now(), now()),
('station_241', 'Number One JAZZ', 'https://n10101m.mediatriple.net/videoonlylive/mtkgeuihrlfwlive/u_stream_5c9e3e06878b9_1/playlist.m3u8', 'Klasik & Kültür', true, now(), now()),
('station_242', 'Number One Türk', 'https://n10101m.mediatriple.net/numberoneturk', 'Pop & Hit', true, now(), now()),
('station_243', 'Number one', 'https://n10101m.mediatriple.net/numberone', 'Pop & Hit', true, now(), now()),
('station_244', 'ORDU FM', 'https://radyo.yayindakiler.com:8012/', 'Yerel', true, now(), now()),
('station_245', 'Onur Radyo', 'http://anadolu.liderhost.com.tr:8094/', 'Dini', true, now(), now()),
('station_246', 'Ostim Radyo', 'https://stream.netradyom.com/radio/8010/radio.mp3%22', 'Yerel', true, now(), now()),
('station_247', 'OĞUZ FM', 'https://radyo.yayin.com.tr:5892/', 'Yerel', true, now(), now()),
('station_248', 'PAL Nostalji', 'https://moondigitaledge.radyotvonline.net/palnostalji/playlist.m3u8', 'Arabesk & Nostalji', true, now(), now()),
('station_249', 'PASH PASH RADYO', 'https://hits.pashpashradio.com:7000/;', 'Kürtçe', true, now(), now()),
('station_250', 'POP 90', 'https://playerservices.streamtheworld.com/api/livestream-redirect/POP90128AAC.aac', 'Pop & Hit', true, now(), now()),
('station_251', 'POP HOME', 'https://moondigitalmaster.radyotvonline.net/pophome/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_252', 'POP LAND', 'https://moondigitaledge.radyotvonline.net/popland/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_253', 'POWER 66', 'https://anadolu.liderhost.com.tr:10921/;', 'Pop & Hit', true, now(), now()),
('station_254', 'POWER EARTH', 'http://listen.powerapp.com.tr/powerearth/abr/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_255', 'POWER TÜRK DANS TÜRKİYE', 'https://listen.powerapp.com.tr/powerturkdans/abr/powerturkdans/128/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_256', 'POWER TÜRK FM', 'https://live.powerapp.com.tr/powerturk/abr/powerturk/128/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_257', 'POWER TÜRK TAPTAZE', 'https://listen.powerapp.com.tr/powerturktaptaze/abr/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_258', 'POWER XL TURKEY', 'https://listen.powerapp.com.tr/powerextralounge/abr/powerextralounge/96/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_259', 'POWERTÜRK SLOW', 'https://listen.powerapp.com.tr/powerturkslow/mpeg/icecast.audio', 'Pop & Hit', true, now(), now()),
('station_260', 'Pal Doğa', 'http://shoutcast.radyogrup.com:1040/;*.mp3', 'Türkü & Halk', true, now(), now()),
('station_261', 'Pal Fm', 'https://ssl4.radyotvonline.com/radyohome/palfmhome.stream/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_262', 'Pal station', 'http://shoutcast.radyogrup.com:1020/', 'Pop & Hit', true, now(), now()),
('station_263', 'Park Fm', 'http://yayin.netradyom.com:8050/PARKFM/', 'Pop & Hit', true, now(), now()),
('station_264', 'Pazarcık', 'http://yayin.pazarcikfm.com:9090/', 'Türkü & Halk', true, now(), now()),
('station_265', 'Pir Yolu', 'http://radyopiryolu.canliyayinda.com:8165/', 'Dini', true, now(), now()),
('station_266', 'Power Dance', 'https://listen.powerapp.com.tr/powerdance/mpeg/icecast.audio', 'Dance & Elektronik', true, now(), now()),
('station_267', 'Power FM Türkiye', 'https://listen.powerapp.com.tr/powerfm/256/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_268', 'Power Gold TR', 'https://live.powerapp.com.tr/powergold/abr/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_269', 'Power Love', 'https://listen.powerapp.com.tr/plove/love.smil/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_270', 'Power POP', 'https://listen.powerapp.com.tr/powerpop/128/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_271', 'Power R&B Hip-Hop', 'https://listen.powerapp.com.tr/powerrbhiphop/256/chunks.m3u8', 'Pop & Hit', true, now(), now()),
('station_272', 'Power dance', 'https://listen.powerapp.com.tr/powerdance/abr/powerdance/128/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_273', 'Power love', 'https://listen.powerapp.com.tr/powerlove/abr/powerlove/128/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_274', 'PowerTürk Akustik', 'https://listen.powerapp.com.tr/powerturkakustik/abr/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_275', 'PowerTürk Dans', 'https://listen.powerapp.com.tr/powerturkdans/abr/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_276', 'Powerturk R&B Hip Hop', 'https://listen.powerapp.com.tr/powerrbhiphop/abr/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_277', 'RADYO 08', 'https://sslyayin.netyayin.net:10931/', 'Yerel', true, now(), now()),
('station_278', 'RADYO 16', 'https://radyo.yayin.com.tr:6038/', 'Pop & Hit', true, now(), now()),
('station_279', 'RADYO 23', 'https://radyo.yayin.com.tr:8280/', 'Yerel', true, now(), now()),
('station_280', 'RADYO 24', 'https://24arabesk.80.yayin.com.tr/', 'Yerel', true, now(), now()),
('station_281', 'RADYO 34', 'https://radyo34.radyotvonline.net/radyo34', 'Pop & Hit', true, now(), now()),
('station_282', 'RADYO 42 FM MEDYA KONYA PR MUSIC TURKIYE', 'https://a8.asurahosting.com/hls/radyo_42_fm_medya_konya_pr_music/live.m3u8', 'Yerel', true, now(), now()),
('station_283', 'RADYO 68', 'https://radyo.yayindakiler.com:4022/', 'Yerel', true, now(), now()),
('station_284', 'RADYO 71', 'https://radyo.yayin.com.tr:5924/', 'Dini', true, now(), now()),
('station_285', 'RADYO 75', 'https://anadolu.liderhost.com.tr/8126/stream', 'Dini', true, now(), now()),
('station_286', 'RADYO 80', 'https://radyo.yayindakiler.com:4064/', 'Pop & Hit', true, now(), now()),
('station_287', 'RADYO 9', 'https://radyo.yayin.com.tr:4010/', 'Pop & Hit', true, now(), now()),
('station_288', 'RADYO 90', 'https://live.radyo.in/9054/stream', 'Pop & Hit', true, now(), now()),
('station_289', 'RADYO AHENK', 'https://yayin.radyomadyo.com:8014/stream', 'Yerel', true, now(), now()),
('station_290', 'RADYO AK', 'https://radyo.yayin.com.tr:8026/', 'Pop & Hit', true, now(), now()),
('station_291', 'RADYO AKDENIZ', 'https://yayin.radyoakdeniz.com/9470/stream', 'Pop & Hit', true, now(), now()),
('station_292', 'RADYO AKUSTİKLAND', 'https://moondigitaledge.radyotvonline.net/akustikland/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_293', 'RADYO ANTALYA', 'https://sslyayin.netyayin.net:8036/', 'Yerel', true, now(), now()),
('station_294', 'RADYO ARMONİ', 'https://radyo.yayindakiler.com:4084/stream', 'Pop & Hit', true, now(), now()),
('station_295', 'RADYO ATILIM', 'https://listen.powerapp.com.tr/radyoatilim/mpeg/icecast.audio', 'Yerel', true, now(), now()),
('station_296', 'RADYO AVARE', 'https://anadolu.liderhost.com.tr:10980/;', 'Pop & Hit', true, now(), now()),
('station_297', 'RADYO B', 'https://radyob.ozelip.com.tr/8042/stream', 'Pop & Hit', true, now(), now()),
('station_298', 'RADYO BAŞAKŞEHİR', 'https://icecast.netmedya.net/rbasaksehir', 'Pop & Hit', true, now(), now()),
('station_299', 'RADYO BAŞKA', 'https://playerservices.streamtheworld.com/api/livestream-redirect/BASKA.mp3', 'Pop & Hit', true, now(), now()),
('station_300', 'RADYO BLACK', 'https://anadolu.liderhost.com.tr:10966/', 'Pop & Hit', true, now(), now()),
('station_301', 'RADYO BU', 'https://radyo.yayindakiler.com:8006/', 'Pop & Hit', true, now(), now()),
('station_302', 'RADYO CLUBBİN', 'https://radyo.yayin.com.tr:6199/', 'Dance & Elektronik', true, now(), now()),
('station_303', 'RADYO D', 'https://radyo.duhnet.tv/radyod', 'Pop & Hit', true, now(), now()),
('station_304', 'RADYO DRK', 'https://stream.zeno.fm/czwwh7xfqm0uv', 'Pop & Hit', true, now(), now()),
('station_305', 'RADYO DUBLE', 'https://radyo.yayindakiler.com:2044/', 'Pop & Hit', true, now(), now()),
('station_306', 'RADYO DÜET', 'https://radyo.yayin.com.tr:6032/stream', 'Pop & Hit', true, now(), now()),
('station_307', 'RADYO EGE HAVALARI', 'http://37.247.98.8/stream/29/', 'Türkü & Halk', true, now(), now()),
('station_308', 'RADYO ENERGY', 'https://trkvz-radyolar.ercdn.net/radyoenergy/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_309', 'RADYO ESTÜ', 'https://ssl120.radyotelekom.com.tr/8024/stream', 'Klasik & Kültür', true, now(), now()),
('station_310', 'RADYO EŞME', 'https://anadolu.liderhost.com.tr:8358/', 'Yerel', true, now(), now()),
('station_311', 'RADYO FENOMEN 2010 LAR', 'https://live.radyofenomen.com/fenomen2010/abr/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_312', 'RADYO FLAS', 'https://radyo.yayindakiler.com:4096/', 'Pop & Hit', true, now(), now()),
('station_313', 'RADYO GERÇEK', 'https://ssl120.radyotelekom.com.tr:8198/', 'Pop & Hit', true, now(), now()),
('station_314', 'RADYO GÜNEŞ', 'https://sssx.radyosfer.com/radyogunes/stream', 'Pop & Hit', true, now(), now()),
('station_315', 'RADYO GÜVEN', 'https://radyo.yayin.com.tr:4098/', 'Pop & Hit', true, now(), now()),
('station_316', 'RADYO HABER', 'https://radyo.yayindakiler.com:4118/', 'Haber', true, now(), now()),
('station_317', 'RADYO HAZAR', 'https://radyo.yayin.com.tr:8286/', 'Pop & Hit', true, now(), now()),
('station_318', 'RADYO KLÜP', 'https://radyo.yayin.com.tr:5894/', 'Klasik & Kültür', true, now(), now()),
('station_319', 'RADYO KOÇ', 'https://stores.powerapp.com.tr/kocschool/mpeg/icecast.audio', 'Klasik & Kültür', true, now(), now()),
('station_320', 'RADYO KTU', 'https://sslyayin.netyayin.net:8076/', 'Klasik & Kültür', true, now(), now()),
('station_321', 'RADYO KİLİM', 'https://sslyayin.netyayin.net:10946/', 'Türkü & Halk', true, now(), now()),
('station_322', 'RADYO LOJİK', 'https://ip20.ozelip.com:9710/', 'Yerel', true, now(), now()),
('station_323', 'RADYO LİVA', 'https://yayin.radyoliva.com:3068/stream', 'Pop & Hit', true, now(), now()),
('station_324', 'RADYO MEGA', 'https://megaradyoiskenderun.ozelip.com/8024/stream', 'Pop & Hit', true, now(), now()),
('station_325', 'RADYO MEYDAN', 'https://live.sinirsizhost.com/8042/stream', 'Yerel', true, now(), now()),
('station_326', 'RADYO MONİ', 'https://radyo.yayin.com.tr:4262/stream', 'Pop & Hit', true, now(), now()),
('station_327', 'RADYO MOOD', 'https://radyo.yayin.com.tr:5862/;', 'Pop & Hit', true, now(), now()),
('station_328', 'RADYO MUĞLA', 'https://radyo.yayindakiler.com:3006/', 'Yerel', true, now(), now()),
('station_329', 'RADYO MÜZEYYEN', 'https://moondigitaledge.radyotvonline.net/muzeyyen/playlist.m3u8', 'Klasik & Kültür', true, now(), now()),
('station_330', 'RADYO NET', 'https://sslyayin.netyayin.net:8068/', 'Pop & Hit', true, now(), now()),
('station_331', 'RADYO NEVŞEHİR', 'https://stream2.rtvtakip.com:7025/', 'Yerel', true, now(), now()),
('station_332', 'RADYO NEŞE', 'https://radyo.yayindakiler.com:2042/', 'Pop & Hit', true, now(), now()),
('station_333', 'RADYO PAUSE', 'https://radyopause.ozelip.com.tr:8040/', 'Pop & Hit', true, now(), now()),
('station_334', 'RADYO SAHİL', 'https://radyo1.radyo-dinle.tc/8056/stream', 'Yerel', true, now(), now()),
('station_335', 'RADYO SARI TRAMVAY', 'http://37.247.98.8/stream/27/', 'Yerel', true, now(), now()),
('station_336', 'RADYO SEVTEK', 'https://sevtekfm.ozelip.com/8020/stream', 'Pop & Hit', true, now(), now()),
('station_337', 'RADYO TALYA', 'https://yayin.radyotalya.com:9424/stream', 'Yerel', true, now(), now()),
('station_338', 'RADYO TUTKU', 'https://sssx.radyosfer.com/tutkuradyo/', 'Pop & Hit', true, now(), now()),
('station_339', 'RADYO TÜRKÜ', 'https://yayin.radyomadyo.com:8008/stream', 'Türkü & Halk', true, now(), now()),
('station_340', 'RADYO VOYAGE', 'http://voyagewmp.radyotvonline.com/;', 'Pop & Hit', true, now(), now()),
('station_341', 'RADYO YANKI', 'https://radyoyanki.ozelip.com:9918/', 'Pop & Hit', true, now(), now()),
('station_342', 'RADYO ZERGAN (47)', 'https://sslyayin.netyayin.net/radyozergan/;', 'Yerel', true, now(), now()),
('station_343', 'RADYO ÇAĞLAR', 'https://sssx.radyosfer.com/radyocaglar/stream', 'Pop & Hit', true, now(), now()),
('station_344', 'RADYO ÇUKUR', 'https://radyo.yayin.com.tr:4060/', 'Yerel', true, now(), now()),
('station_345', 'RADYO ÜLKÜ', 'https://radyo.yayin.com.tr:4006/', 'Yerel', true, now(), now()),
('station_346', 'RADYO İMZA', 'https://radyo.radyoimza.com:8016/', 'Pop & Hit', true, now(), now()),
('station_347', 'RADYO ŞAMPİYON', 'https://radyo.yayin.com.tr:4106/stream', 'Spor', true, now(), now()),
('station_348', 'RADYOTÜRK', 'https://radyo.yayindakiler.com:4028/', 'Pop & Hit', true, now(), now()),
('station_349', 'RADİO 5 LEGEND', 'https://radiocom.80.yayin.com.tr/', 'Pop & Hit', true, now(), now()),
('station_350', 'RAP HOME', 'http://37.247.98.8/stream/606/', 'Dance & Elektronik', true, now(), now()),
('station_351', 'RELAX HOME', 'https://moondigitaledge.radyotvonline.net/relaxhome/playlist.m3u8', 'Arabesk & Nostalji', true, now(), now()),
('station_352', 'REPLAY NEWS - Türkçe Her 5 dakikada haber radyosu', 'https://replaynewstr.ice.infomaniak.ch/replaynewstr-128.mp3', 'Haber', true, now(), now()),
('station_353', 'ROCK FM', 'https://rockfm.rockfm.com.tr:9450/stream', 'Rock & Alternatif', true, now(), now()),
('station_354', 'ROMANTİK TÜRK', 'https://radyo.yayin.com.tr:6042/', 'Pop & Hit', true, now(), now()),
('station_355', 'RS FM', 'http://nfw.video.ria.ru/flv/audio.aspx?ID=99244423&type=mp3', 'Pop & Hit', true, now(), now()),
('station_356', 'RUN ON AİR', 'https://stream.radio.co/s5865f80fd/listen', 'Dance & Elektronik', true, now(), now()),
('station_357', 'Radio 44', 'https://radyo44.80.yayin.com.tr/stream', 'Pop & Hit', true, now(), now()),
('station_358', 'Radio 5 Turkey', 'https://radyo.yayin.com.tr/tunein/radiotrc.asx', 'Pop & Hit', true, now(), now()),
('station_359', 'Radio Antalya', 'https://my.radiolize.com/radio/8000/radio.mp3', 'Yerel', true, now(), now()),
('station_360', 'Radio Ava Turkiye', 'http://play.markaradyo.com:8002/stream', 'Pop & Hit', true, now(), now()),
('station_361', 'Radio Glamorize', 'https://live.radioglamorize.com/stream1', 'Pop & Hit', true, now(), now()),
('station_362', 'Radio Life Kayseri', 'https://yayin2.canliyayin.org:10990/;*.mp3', 'Yerel', true, now(), now()),
('station_363', 'Radio Light', 'http://yayin.radiolight.net:8005/live', 'Pop & Hit', true, now(), now()),
('station_364', 'Radio Line', 'https://online.radioline.fm:8443/stream', 'Pop & Hit', true, now(), now()),
('station_365', 'Radio Mydonose', 'https://29083.live.streamtheworld.com/RADIO_MYDONOSE128AAC.aac?/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_366', 'Radio Wanderlust', 'http://radyo.yayin.com.tr:5898/', 'Pop & Hit', true, now(), now()),
('station_367', 'Radioo Mega site', 'http://mega.netradyom.com:7900/listen.pls', 'Pop & Hit', true, now(), now()),
('station_368', 'Radyo 13', 'https://radyo.yayindakiler.com:3050/stream?/;stream.mp3', 'Yerel', true, now(), now()),
('station_369', 'Radyo 2000 Erzincan', 'https://radyo.yayindakiler.com:3030/stream?/;stream.mp3', 'Yerel', true, now(), now()),
('station_370', 'Radyo 35', 'https://yayin.turkhosted.com/6012/stream', 'Pop & Hit', true, now(), now()),
('station_371', 'Radyo 45''lik', 'http://stream.radyo45lik.com:4545/', 'Pop & Hit', true, now(), now()),
('station_372', 'Radyo 45’lik, 1970’ler, 1980’ler ve 1990’lar', 'https://stream.radyo45lik.com:4545/', 'Pop & Hit', true, now(), now()),
('station_373', 'Radyo 7', 'http://46.20.3.250/;stream', 'Dini', true, now(), now()),
('station_374', 'Radyo A (Radyo Anadolu Üniversitesi)', 'http://canli.radyoa.anadolu.edu.tr:44445/Radyo_A_MP3', 'Klasik & Kültür', true, now(), now()),
('station_375', 'Radyo Alaturka', 'https://yayin.jumboserver.net:9100/stream', 'Türkü & Halk', true, now(), now()),
('station_376', 'Radyo Alevi Canlar', 'https://alevifm.80.yayin.com.tr/', 'Dini', true, now(), now()),
('station_377', 'Radyo Arkadaş', 'https://ssl120.radyotelekom.com.tr/9998/stream', 'Pop & Hit', true, now(), now()),
('station_378', 'Radyo Banko Fm', 'http://yayin.netradyom.com:8050/RADYOBANKO', 'Pop & Hit', true, now(), now()),
('station_379', 'Radyo Bilkent', 'https://stream.netradyom.com/listen/radyobilkent/radio.mp3', 'Klasik & Kültür', true, now(), now()),
('station_380', 'Radyo Can', 'http://yayin2.yayindakiler.com:4174/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_381', 'Radyo D', 'https://moondigitaledge2.radyotvonline.net/radyod/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_382', 'Radyo Delal', 'https://wowza1.radyotvonline.com/idilpr/radyodelal.stream/playlist.m3u8', 'Kürtçe', true, now(), now()),
('station_383', 'Radyo Duygusal', 'https://radyoduygusal.kesintisizyayin.com:9596/;*.nsv', 'Arabesk & Nostalji', true, now(), now()),
('station_384', 'Radyo EN', 'https://yayin2.canliyayin.org:7222/;', 'Pop & Hit', true, now(), now()),
('station_385', 'Radyo Ekin', 'https://yayin.turkhosted.com/6006/stream', 'Türkü & Halk', true, now(), now()),
('station_386', 'Radyo Eksen', 'https://dygedge.radyotvonline.net/radyoeksen/playlist.m3u8', 'Rock & Alternatif', true, now(), now()),
('station_387', 'Radyo Eksen 96.2', 'http://eksenwmp.radyotvonline.com/;stream.mp3', 'Rock & Alternatif', true, now(), now()),
('station_388', 'Radyo Esenler', 'https://yayin2.canliyayin.org:10978/;', 'Yerel', true, now(), now()),
('station_389', 'Radyo Fenomen', 'https://live.radyofenomen.com/fenomen/128/icecast.audio', 'Pop & Hit', true, now(), now()),
('station_390', 'Radyo Fenomen Clubbin', 'https://live.radyofenomen.com/fenomenclubbin/128/icecast.audio', 'Pop & Hit', true, now(), now()),
('station_391', 'Radyo Fenomen Dans', 'https://live.radyofenomen.com/fenomendans/abr/playlist.m3u8', 'Dance & Elektronik', true, now(), now()),
('station_392', 'Radyo Fikir', 'https://studio21.radiolize.com/radio/8100/radio.mp3?1647021999', 'Yerel', true, now(), now()),
('station_393', 'Radyo Fıtrat', 'http://radyofitrat.radyotvonline.net/', 'Dini', true, now(), now()),
('station_394', 'Radyo Gol', 'https://moondigitaledge.radyotvonline.net/radyogol/playlist.m3u8', 'Spor', true, now(), now()),
('station_395', 'Radyo Göktürk', 'https://ip231.ozelip.com:8004/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_396', 'Radyo Gökçeada', 'https://radyo.yayin.com.tr:6179/;', 'Yerel', true, now(), now()),
('station_397', 'Radyo Gül', 'http://yayin2.canliyayin.org:8866/;*.mp3', 'Dini', true, now(), now()),
('station_398', 'Radyo Hakkın Sesi', 'https://radio.mihr.com/radio/8010/hakkinsesi', 'Dini', true, now(), now()),
('station_399', 'Radyo Hayat', 'http://live4.radyotvonline.com:9450/', 'Pop & Hit', true, now(), now()),
('station_400', 'Radyo Hidayet Çağı', 'https://radio.mihr.com/radio/8000/radio.mp3', 'Dini', true, now(), now()),
('station_401', 'Radyo ILEF Ankara', 'http://radyo.cc.ankara.edu.tr:8089/listen.pls', 'Klasik & Kültür', true, now(), now()),
('station_402', 'Radyo Karabalı', 'https://radyokarabali.ozelip.com:9884/;', 'Yerel', true, now(), now()),
('station_403', 'Radyo MODyAn', 'http://stream.radio.co/s55d598f42/listen', 'Pop & Hit', true, now(), now()),
('station_404', 'Radyo Maranata', 'http://medya.radyomaranata.com:8005/live', 'Dini', true, now(), now()),
('station_405', 'Radyo Mars', 'https://yayin.radyomadyo.com:9400/stream', 'Pop & Hit', true, now(), now()),
('station_406', 'Radyo Megasite', 'http://mega.netradyom.com:7900/;', 'Pop & Hit', true, now(), now()),
('station_407', 'Radyo Mori', 'https://amed.ozelip.com/8040/stream', 'Pop & Hit', true, now(), now()),
('station_408', 'Radyo Munzur 97.7', 'http://yayin1.yayindakiler.com:3002/;stream.nsv', 'Yerel', true, now(), now()),
('station_409', 'Radyo Nebi', 'https://anadolu.liderhost.com.tr/9006/stream', 'Dini', true, now(), now()),
('station_410', 'Radyo Nida', 'https://anadolu.liderhost.com.tr/8106/stream', 'Dini', true, now(), now()),
('station_411', 'Radyo Nostaljinin Sesi', 'http://eu8.fastcast4u.com/proxy/eskininadami/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_412', 'Radyo ODTU', 'http://stream.radyoodtu.com.tr/;', 'Klasik & Kültür', true, now(), now()),
('station_413', 'Radyo ODTU - Rock', 'http://stream.radyoodtu.com.tr/rock', 'Klasik & Kültür', true, now(), now()),
('station_414', 'Radyo Odtu Easy', 'https://stream3.radyoodtu.com.tr:8000/easy', 'Klasik & Kültür', true, now(), now()),
('station_415', 'Radyo S', 'http://icecast.netmedya.net/radyos', 'Yerel', true, now(), now()),
('station_416', 'Radyo Seymen', 'https://yayin.radyoseymen.com.tr:1070/stream', 'Türkü & Halk', true, now(), now()),
('station_417', 'Radyo Sinerji', 'https://radio.guventechnology.com/9994/stream', 'Pop & Hit', true, now(), now()),
('station_418', 'Radyo Slow Time', 'http://46.20.7.103:8040/;', 'Arabesk & Nostalji', true, now(), now()),
('station_419', 'Radyo Spor', 'https://moondigitaledge.radyotvonline.net/radyospor/playlist.m3u8', 'Spor', true, now(), now()),
('station_420', 'Radyo Sputnik', 'https://icecast-rian.cdnvideo.ru/voicestm', 'Haber', true, now(), now()),
('station_421', 'Radyo Taksi', 'https://live.radyo.in/8006/stream', 'Pop & Hit', true, now(), now()),
('station_422', 'Radyo Trafik 104.2 Ankara', 'http://live2.radyotvonline.com:8000/', 'Pop & Hit', true, now(), now()),
('station_423', 'Radyo Trafik İstanbul', 'http://37.247.100.118/stream/157/', 'Pop & Hit', true, now(), now()),
('station_424', 'Radyo Trio', 'http://radyotrio.radyotvonline.net/radyotrio', 'Pop & Hit', true, now(), now()),
('station_425', 'Radyo Turkuvaz', 'https://trkvz-radyolar.ercdn.net/radyoturkuvaz/playlist.m3u8', 'Türkü & Halk', true, now(), now()),
('station_426', 'Radyo Vatan Türkü', 'http://95.0.173.195:9000/turku', 'Türkü & Halk', true, now(), now()),
('station_427', 'Radyo Venüs', 'https://stream2.rtvtakip.com:7005/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_428', 'Radyo Viva', 'https://edge1.radyotvonline.net/shoutcast/play/radyoviva', 'Pop & Hit', true, now(), now()),
('station_429', 'Radyo Voyage', 'https://ssldyg.radyotvonline.com/pozitif/smil:voyage.smil/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_430', 'Radyo Yalova', 'https://studio25.radiolize.com/radio/8200/radio.mp3', 'Yerel', true, now(), now()),
('station_431', 'Radyo light', 'https://yayin.radiolight.net:8005/live', 'Pop & Hit', true, now(), now()),
('station_432', 'Radyo İlahi', 'https://anadolu.liderhost.com.tr:10994/;', 'Dini', true, now(), now()),
('station_433', 'Radyo Şiran', 'https://live.radyositesihazir.com/8078/stream', 'Türkü & Halk', true, now(), now()),
('station_434', 'RadyoVoyage', 'http://voyagesc.radyotvonline.com/', 'Pop & Hit', true, now(), now()),
('station_435', 'Retro Turk', 'https://playerservices.streamtheworld.com/api/livestream-redirect/RETROTURK_SC?/;', 'Pop & Hit', true, now(), now()),
('station_436', 'Ribat FM', 'http://yayin1.canliyayin.org:7010/;*.mp3', 'Dini', true, now(), now()),
('station_437', 'Risalet Radyo', 'https://eustr73.mediatriple.net/videoonlylive/mtikoimxnztxlive/broadcast_5e3c1520b2626.smil/playlist.m3u8', 'Dini', true, now(), now()),
('station_438', 'Romantik SES Sakarya', 'https://radyo.romantikses.com/romantiksessakary/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_439', 'Romantik Ses ISPARTA', 'https://radyo.romantikses.com/romantiksesispart/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_440', 'S1lhoutte - Slow FM', 'https://anadolu.liderhost.com.tr:10973/', 'Arabesk & Nostalji', true, now(), now()),
('station_441', 'S1lhoutte Arabesk FM', 'https://yayin.radyoarabesk.com.tr:8000/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_442', 'SES FM', 'https://yayin.sesfm.com.tr:8090/stream', 'Yerel', true, now(), now()),
('station_443', 'SEYDİŞEHİR FM', 'https://radyo.yayin.com.tr:4142/strem', 'Yerel', true, now(), now()),
('station_444', 'SEÇ FM', 'https://live.radyo.in/8066/stream', 'Pop & Hit', true, now(), now()),
('station_445', 'SIZIR FM', 'http://stream.radiojar.com/tamm1f7kk48uv', 'Yerel', true, now(), now()),
('station_446', 'SOFT RADYO', 'https://radyo.softradyo.com/1140/stream', 'Pop & Hit', true, now(), now()),
('station_447', 'SUPER FM 2 TURKEY', 'https://playerservices.streamtheworld.com/api/livestream-redirect/SUPER2_SC?/', 'Pop & Hit', true, now(), now()),
('station_448', 'SZC', 'https://cdn.tecostream.xyz/Sozcu_Tv.m3u8', 'TV (Video)', true, now(), now()),
('station_449', 'Serhat FM', 'http://yayin.serhatfm.com:9150/stream', 'Yerel', true, now(), now()),
('station_450', 'Sezen Radyo', 'http://radyo1.radyo-dinle.tc:8038/', 'Arabesk & Nostalji', true, now(), now()),
('station_451', 'Show radio', 'https://moondigitaledge.radyotvonline.net/show/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_452', 'Slow Turk', 'https://radyo.duhnet.tv/ak_dtvh_slowturk', 'Arabesk & Nostalji', true, now(), now()),
('station_453', 'Standart.fm', 'https://moondigitaledge.radyotvonline.net/standartfm/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_454', 'Super Fm', 'https://playerservices.streamtheworld.com/api/livestream-redirect/SUPER_FM_SC', 'Pop & Hit', true, now(), now()),
('station_455', 'SÜPER SHOW RADYO', 'https://sslyayin.netyayin.net:6065/', 'Pop & Hit', true, now(), now()),
('station_456', 'Süper 2 FM', 'https://playerservices.streamtheworld.com/api/livestream-redirect/SUPER2_SC.mp3', 'Pop & Hit', true, now(), now()),
('station_457', 'Süper FM', 'http://provisioning.streamtheworld.com/pls/SUPER_FMAAC.pls', 'Pop & Hit', true, now(), now()),
('station_458', 'Süper Fm', 'https://playerservices.streamtheworld.com/api/livestream-redirect/SUPER2_SC', 'Pop & Hit', true, now(), now()),
('station_459', 'TGRT FM', 'http://b01c02nl.mediatriple.net/videoonlylive/mtsxxkzwwuqtglive/broadcast_5fead000e2128.smil/playlist.m3u8', 'Haber', true, now(), now()),
('station_460', 'TOKAT FM', 'https://sssx.radyosfer.com/tokatfm/stream', 'Yerel', true, now(), now()),
('station_461', 'TRD 4', 'https://stream.zeno.fm/x5n4sfyy9nhvv', 'Yerel', true, now(), now()),
('station_462', 'TRT Antalya', 'https://radio-trtantalya.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_463', 'TRT Diyarbakır', 'https://radio-trtgap.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_464', 'TRT Erzurum', 'https://radio-trterzurum.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_465', 'TRT FM', 'https://trt.radyotvonline.net/trtfm', 'TRT', true, now(), now()),
('station_466', 'TRT Memleketim FM', 'https://radio-trtmemleketimfm.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_467', 'TRT NAĞME', 'https://tv-trtmuzik.medya.trt.com.tr/master_720.m3u8', 'TRT', true, now(), now()),
('station_468', 'TRT Nağme', 'https://rd-trtnagme.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_469', 'TRT Radyo 1', 'https://trt.radyotvonline.net/trt1', 'TRT', true, now(), now()),
('station_470', 'TRT Radyo Haber', 'https://radio-trtradyohaber.live.trt.com.tr/master.m3u8', 'Haber', true, now(), now()),
('station_471', 'TRT Radyo Kurdî', 'https://radio-trtradyo6.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_472', 'TRT TSR', 'https://radio-trttsr.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_473', 'TRT Trabzon', 'https://radio-trttrabzon.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_474', 'TRT Türkü', 'https://rd-trtturku.medya.trt.com.tr/master_128.m3u8', 'TRT', true, now(), now()),
('station_475', 'TRT Çukurova', 'https://radio-trtcukurova.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_476', 'TRT3', 'http://rd-trtradyo3.medya.trt.com.tr/master.m3u8', 'TRT', true, now(), now()),
('station_477', 'TURKUVAZ EFSANE', 'https://trkvz-radyolar.ercdn.net/turkuvazefsane/playlist.m3u8', 'Arabesk & Nostalji', true, now(), now()),
('station_478', 'TURKUVAZ NOSTALJİ', 'https://trkvz-radyolar.ercdn.net/turkuvaznostalji/playlist.m3u8', 'Arabesk & Nostalji', true, now(), now()),
('station_479', 'TURKUVAZ ROMANTİK', 'https://trkvz-radyolar.ercdn.net/turkuvazromantik/playlist.m3u8', 'Arabesk & Nostalji', true, now(), now()),
('station_480', 'Tarkan', 'https://stream.pcradio.ru/tarkan-hi', 'Pop & Hit', true, now(), now()),
('station_481', 'Tarsus FM', 'https://tarsusfm.80.yayin.com.tr//stream', 'Yerel', true, now(), now()),
('station_482', 'Tezene', 'http://37.247.98.8/stream/22/.mp3?%26token=Bsx3vK2u28-xMp98IZDV2Q%26expires=1618686860%27%20type=%27audio/mp3%27&rd2=%27https://radyo.vip/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_483', 'TheRockRadio', 'https://ssl4.radyotvonline.com/radyohome/therockradio.stream/playlist.m3u8', 'Rock & Alternatif', true, now(), now()),
('station_484', 'Trt Spor', 'https://rd-trtradyo1.medya.trt.com.tr/master_128.m3u8', 'TRT', true, now(), now()),
('station_485', 'Turku Radyo', 'http://radyo.turkuradyo.net:4591/listen.pls', 'Türkü & Halk', true, now(), now()),
('station_486', 'Turkuaz Anadolu', 'https://trkvz-radyolar.ercdn.net/turkuvazanadolu/playlist.m3u8', 'Türkü & Halk', true, now(), now()),
('station_487', 'Turkuvaz Anadolu', 'http://trkvz-radyolar.ercdn.net/turkuvazanadolu/Playlist.m3u8', 'Türkü & Halk', true, now(), now()),
('station_488', 'Turkuvaz Musiki', 'https://trkvz-radyolar.ercdn.net/turkuvazmusiki/playlist.m3u8', 'Türkü & Halk', true, now(), now()),
('station_489', 'Türkiyem FM', 'https://server7.streamserver24.com/proxy/turkiyemfm?mp=/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_490', 'Türkü Radyo', 'https://eu8.fastcast4u.com/proxy/ugur4129?mp=/1', 'Türkü & Halk', true, now(), now()),
('station_491', 'TürküRadyo', 'https://yayin.turkhosted.com/4591/stream', 'Türkü & Halk', true, now(), now()),
('station_492', 'Türkülerle Türkiye', 'http://37.247.98.8/stream/22/;', 'Türkü & Halk', true, now(), now()),
('station_493', 'TİME TÜRK', 'https://radyo.yayindakiler.com:4195/', 'Pop & Hit', true, now(), now()),
('station_494', 'TİRYAKİ FM', 'https://yayin.turkhosted.com:6056/mp3', 'Arabesk & Nostalji', true, now(), now()),
('station_495', 'ULUSAL ARABESK', 'https://radio.guventechnology.com/9334/stream', 'Arabesk & Nostalji', true, now(), now()),
('station_496', 'Vav Radyo', 'https://trkvz-radyolar.ercdn.net/radyovav/playlist.m3u8', 'Dini', true, now(), now()),
('station_497', 'Veng RADYO', 'https://live.radyo.in/8012/stream', 'Kürtçe', true, now(), now()),
('station_498', 'Virgin Radio Türkiye', 'http://29103.live.streamtheworld.com/VIRGIN_RADIO_SC', 'Pop & Hit', true, now(), now()),
('station_499', 'VİBE STATİON', 'https://stream.zeno.fm/528but9e7motv', 'Dance & Elektronik', true, now(), now()),
('station_500', 'VİRGİN RADYO', 'https://playerservices.streamtheworld.com/api/livestream-redirect/VIRGIN_RADIO_ITUNES.mp3', 'Pop & Hit', true, now(), now()),
('station_501', 'VİZYON NOSTALJİ', 'https://stream.netradyom.com/radio/7090/radio.mp3/;', 'Arabesk & Nostalji', true, now(), now()),
('station_502', 'WORLD HİTS', 'http://37.247.98.8/stream/34/', 'Pop & Hit', true, now(), now()),
('station_503', 'X Radio', 'http://yayin.radyomadyo.com:8770/', 'Pop & Hit', true, now(), now()),
('station_504', 'YENİ POP', 'https://playerservices.streamtheworld.com/api/livestream-redirect/SC006_SO1AAC.aac', 'Pop & Hit', true, now(), now()),
('station_505', 'YILDIZ FM', 'https://radyo.yayin.com.tr:5940/', 'Yerel', true, now(), now()),
('station_506', 'YOZGAT FM', 'https://sslyayin.netyayin.net:10921/', 'Yerel', true, now(), now()),
('station_507', 'Yaren FM', 'https://yarenfmn.80.yayin.com.tr//stream', 'Yerel', true, now(), now()),
('station_508', 'Yeni Radyo Nostaljinin Sesi', 'https://eu9.fastcast4u.com/tunein/eskininadami.pls', 'Arabesk & Nostalji', true, now(), now()),
('station_509', 'a PARA', 'https://trkvz-radyolar.ercdn.net/apararadyo/playlist.m3u8', 'Haber', true, now(), now()),
('station_510', 'andromeda radio', 'https://radyo1.radyo-dinle.tc/andromedaradio/stream', 'Dance & Elektronik', true, now(), now()),
('station_511', 'baba radyo', 'http://officialbabaradyo.radyotvonline.net/babaofficial', 'Pop & Hit', true, now(), now()),
('station_512', 'dinamo.fm caffe', 'http://channels.dinamo.fm/caffe-mp3', 'Dance & Elektronik', true, now(), now()),
('station_513', 'dinamo.fm deep', 'http://channels.dinamo.fm/deep-mp3', 'Dance & Elektronik', true, now(), now()),
('station_514', 'dinamo.fm discotheque', 'http://channels.dinamo.fm/discotheque-mp3', 'Dance & Elektronik', true, now(), now()),
('station_515', 'dinamo.fm fluent', 'http://channels.dinamo.fm/fluent-mp3', 'Dance & Elektronik', true, now(), now()),
('station_516', 'dinamo.fm legacy', 'http://channels.dinamo.fm/legacy-mp3', 'Dance & Elektronik', true, now(), now()),
('station_517', 'dinamo.fm live from minimuzikhol', 'http://channels.dinamo.fm/mmradyo-mp3', 'Dance & Elektronik', true, now(), now()),
('station_518', 'dinamo.fm locodyno', 'http://channels.dinamo.fm/locodyno-mp3', 'Dance & Elektronik', true, now(), now()),
('station_519', 'dinamo.fm sleep', 'http://channels.dinamo.fm/sleep-mp3', 'Dance & Elektronik', true, now(), now()),
('station_520', 'dinamo.fm smog', 'http://channels.dinamo.fm/smog-mp3', 'Dance & Elektronik', true, now(), now()),
('station_521', 'efkar', 'https://playerservices.streamtheworld.com/api/livestream-redirect/EFKAR.mp3', 'Pop & Hit', true, now(), now()),
('station_522', 'https://turkmedya-live.ercdn.net/tv24/tv24.m3u8', 'https://turkmedya-live.ercdn.net/tv24/tv24.m3u8', 'TV (Video)', true, now(), now()),
('station_523', 'imaj fm', 'https://sslyayin.netyayin.net/imajfm/stream/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_524', 'joytürk fm', 'https://playerservices.streamtheworld.com/pls/JOY_TURK.pls', 'Pop & Hit', true, now(), now()),
('station_525', 'literal', 'https://playerservices.streamtheworld.com/api/livestream-redirect/LITERAL128AAC.aac', 'Klasik & Kültür', true, now(), now()),
('station_526', 'lokum fm', 'http://37.247.98.9/stream/493/?/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_527', 'loops radio', 'https://progressive.ozelip.com/7670/stream', 'Dance & Elektronik', true, now(), now()),
('station_528', 'meteorolojinin sesi', 'http://radyomgm.canliyayinda.com/;stream.mp3', 'Genel', true, now(), now()),
('station_529', 'oyunpiyat', 'https://yayin.hostwin.net/8888/stream%20%20oyunpiyatfm', 'Genel', true, now(), now()),
('station_530', 'playdanceradio', 'https://radyo1.radyo-dinle.tc/playdanceradio/stream', 'Dance & Elektronik', true, now(), now()),
('station_531', 'pop 90 turkey', 'http://provisioning.streamtheworld.com/pls/POP90AAC.pls', 'Pop & Hit', true, now(), now()),
('station_532', 'power love', 'https://listen.powerapp.com.tr/powerlove/abr/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_533', 'power plus', 'https://listen.powerapp.com.tr/powerplus/abr/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_534', 'powerturk', 'https://live.powerapp.com.tr/powerturk/abr/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_535', 'radio Megasite', 'http://yayin.asymedya.com:8020/listen.pls', 'Pop & Hit', true, now(), now()),
('station_536', 'radyo mezopotamya', 'https://anadolu.liderhost.com.tr/9404/stream', 'Kürtçe', true, now(), now()),
('station_537', 'radyo mydonose', 'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_MYDONOSE128AAC.aac?/;stream.mp3', 'Pop & Hit', true, now(), now()),
('station_538', 'radyo viva', 'https://radyoviva.radyotvonline.net/radyovivaaac', 'Pop & Hit', true, now(), now()),
('station_539', 'retro turk', 'http://provisioning.streamtheworld.com/pls/RETROTURKAAC.pls', 'Pop & Hit', true, now(), now()),
('station_540', 'rock station', 'https://playerservices.streamtheworld.com/api/livestream-redirect/ROCK_STATION128AAC.aac?/;stream.mp3', 'Rock & Alternatif', true, now(), now()),
('station_541', 'ÇEŞME VİKİNG RADYO', 'https://ip169.ozelip.com/8432/stream', 'Yerel', true, now(), now()),
('station_542', 'ÇINAR FM', 'https://sslyayin.netyayin.net:10992/', 'Yerel', true, now(), now()),
('station_543', 'ÖMÜR RADYO', 'https://live.sinirsizhost.com/8036/stream', 'Yerel', true, now(), now()),
('station_544', 'Özel FM', 'https://ozelfm.80.yayin.com.tr/;stream/1', 'Yerel', true, now(), now()),
('station_545', 'ÜLKÜ RADYO', 'https://radyo.yayindakiler.com:4112/stream.mp3', 'Yerel', true, now(), now()),
('station_546', 'İNCİTEK FM', 'https://radyo.yayindakiler.com:4204/', 'Yerel', true, now(), now()),
('station_547', 'İTÜ Klasik', 'http://160.75.86.29:8088/ituklasikmp3', 'Klasik & Kültür', true, now(), now()),
('station_548', 'İTÜ Radyosu Rock', 'http://160.75.86.29:8095/', 'Rock & Alternatif', true, now(), now()),
('station_549', 'İstanbul FM', 'https://yayin.istanbulfm.com.tr/istanbulfm/playlist.m3u8', 'Pop & Hit', true, now(), now()),
('station_550', 'Şafak Radyo', 'http://safakradyo.com:2626/;', 'Dini', true, now(), now()),
('station_551', 'اذاعة القرآن الكريم 🇹🇷', 'http://stream.radiojar.com/0tpy1h0kxtzuv', 'Dini', true, now(), now())
ON CONFLICT ("streamUrl") DO NOTHING;
